Repository madewithml/guides, pull requests merged in 2020-10, with the labels that each got.

#1 Starter Template.
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/tutorial_request.md
  .github/stale.yml
  .github/worfklows/greetings.yml
  .github/worfklows/mk-docs-build.yml
  .github/worfklows/mk-docs-deploy.yml
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  Readme.md
  assets/banner.png
  data/README.md
  docs/mkdkocs.yml
  docs/requirements.txt
  docs/templates/contributing.md
  docs/templates/index.md
  requirements.txt
Labels: documentation, enhancement

#5 Fixes workflows
  .github/workflows/greetings.yml
  .github/workflows/mk-docs-build.yml
  .github/workflows/mk-docs-deploy.yml
Labels: bug

#6 Fixes main
  .github/workflows/mk-docs-build.yml
  .github/workflows/mk-docs-deploy.yml
  docs/mkdocs.yml
Labels: bug, documentation

#7 Initial draft
  CONTRIBUTING.md
Labels: documentation

#8 Creates basic structure
  projects/deep_learning_computer_vision/README.md
  projects/deep_learning_nlp/README.md
  projects/image_processing/README.md
  projects/machine_learning/README.md
  projects/natural_language_processing/README.md
  projects/reinforcement_learning/README.md
Labels: maintainence

#12 Basic Project Setup.
  .github/ISSUE_TEMPLATE/maintainence_feedback.md
  .github/workflows/greetings.yml
  .gitmodules
  .nojekyll
  CONTRIBUTING.md
  Readme.md
  docs/templates/contributing.md
  docs/templates/index.md
Labels: documentation, maintainence

#20 [Some Test] CI Action for requirments check.
  .github/workflows/requirements_check.yml
  requirements.txt
Labels: maintainence

#18 Fixes .md files.
  .github/ISSUE_TEMPLATE/maintainence_feedback.md
  .github/PULL_REQUEST_TEMPLATE.md
  Readme.md
  projects/deep_learning_computer_vision/README.md
  projects/deep_learning_nlp/README.md
  projects/image_processing/README.md
  projects/machine_learning/README.md
  projects/natural_language_processing/README.md
  projects/reinforcement_learning/README.md
Labels: maintainence

#24 Migrates repository to guides adds CI for Requirements
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/requirements_check.yml
  CONTRIBUTING.md
  Readme.md
  docs/mkdocs.yml
  guides/deep_learning_computer_vision/README.md
  guides/deep_learning_nlp/README.md
  guides/image_processing/README.md
  guides/machine_learning/README.md
  guides/natural_language_processing/README.md
  guides/reinforcement_learning/README.md
  requirements.txt
  requirements/requirements-linux.txt
  requirements/requirements-mac.txt
  requirements/requirements-win.txt
Labels: maintainence

#25 Remove mkdocs
  .github/workflows/mk-docs-build.yml
  .github/workflows/mk-docs-deploy.yml
  CNAME
  docs/mkdocs.yml
  docs/requirements.txt
  docs/templates/contributing.md
  docs/templates/index.md
Labels: documentation, maintainence
